### ISSUE TITLE
Upload old chat-core releases to artifactory.qiscus.com

### ISSUE THREAD

**Issue by paulbehrisch** [qiscus/qiscus-sdk-android#95]
I am getting the following error when trying to install chat-core:1.3.2

<code>
> Could not GET 'https://dl.bintray.com/qiscustech/maven/com/qiscus/sdk/chat-core/1.3.2/chat-core-1.3.2.pom';. Received status code 403 from server: Forbidden 
</code>

Bintray was official deprecated as per the official announcement https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

In this commit you have moved away from Bintray to Artifactory
https://github.com/qiscus/qiscus-sdk-android/commit/7847a5e05b50d0b897dbbf608c6c29e42b7ba395

The current documentation shows this snippet:

    allprojects { 
        repositories {  
             maven { url "https://artifactory.qiscus.com/artifactory/qiscus-library-open-source" } 
        } 
    }

However, this URL https://artifactory.qiscus.com/artifactory/qiscus-library-open-source/com/qiscus/sdk/chat-core/ has no releases before `1.3.27`. Could you please upload the old releases?

<img width="1094" alt="Screen Shot 2021-05-06 at 14 11 58" src="https://user-images.githubusercontent.com/50549468/117240812-07312500-ae75-11eb-8242-a60923da3d0f.png">

**Comment by hexinlai** [comment]
Hitting the same issue as above, please help to resolve!

**Comment by adicatur** [comment]
Hi @hexinlai you can use our latest version, you can check our releases through this link https://github.com/qiscus/qiscus-sdk-android/releases

**Comment by hexinlai** [comment]
Hi @adicatur , no we are NOT prepared for the latest version yet, as there is another dependency on top of that. Please help to upload v1.3.2 so our development wont be blocked, we will analyze the change scope for the new version after that. Thanks!

**Comment by adicatur** [comment]
Hi @hexinlai for this version 1.3.2x we actually already supported since this version 
https://github.com/qiscus/qiscus-sdk-android/releases/tag/1.3.28

but we recommend using the latest one: https://github.com/qiscus/qiscus-sdk-android/releases/tag/1.3.30

since this version we have a fix for android 11 issue 

Regards

**Comment by hexinlai** [comment]
Hi @adicatur, the context is our dependency on the top is com.halodoc:madura:1.1.6, it uses chat-core-1.3.2, which we cannot change or simply replace.

Pleases help to upload chat-core-1.3.2, so that we can solve this issue before we turn to the upgrade solution, as this issue has stopped us for a week already.

Thanks!

**Comment by adicatur** [comment]
Hi @hexinlai we check the Halodoc already uses 1.3.30, can you coordinate with your internal team?

Regards
